# Generated by Django 5.1.1 on 2024-11-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
