# Generated by Django 5.1.1 on 2024-12-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_peliculas_descripcion_peliculas_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='imagen_trailer',
            field=models.ImageField(blank=True, null=True, upload_to='trailers'),
        ),
    ]
