# Generated by Django 5.1.1 on 2024-12-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_peliculas_imagen_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='total_descuento',
        ),
        migrations.AddField(
            model_name='ventas',
            name='codigo_descuento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='precio_entrada',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total_final',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total_original',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
